### ISSUE TITLE
Cura 4.9 Beta Support

### ISSUE THREAD

**Issue by DivingDuck** [smartavionics/RawMouse#13]
Hello @smartavionics,
 
I hope, you are well. I got an error by testing Cura 4.9 Beta.

cura.log:
```
2021-04-08 09:29:29,483 - ERROR - [MainThread] RawMouse.RawMouse._start [188]: Exception initialising profile: No module named 'hid'
2021-04-08 09:29:29,484 - WARNING - [MainThread] RawMouse.RawMouse._start [211]: No mouse found!
2021-04-08 09:29:29,489 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin RawMouse
```
Best regards,
DD

System: Windows 10 pro 64bit, Cura: 4.9Beta

**Comment by smartavionics** [comment]
Hi, yes, that's because Cura 4.9 is using a later version of Python than that expected by RawMouse. I will be updating RawMouse to make it compatible some time. First I need to get my Cura builds working with the same Python version.

**Comment by DivingDuck** [comment]
Thanks for your info. Take all time you need.

**Comment by smartavionics** [comment]
I have updated the master branch, it should now work with Cura 4.9 beta.

**Comment by DivingDuck** [comment]
Thanks again, the plugin is working fine with Cura 4.9 beta.

The mouse had no fluid movements after starting Cura the first time but with the second start everything was fine (in case if one ask for this behavior)

**Comment by smartavionics** [comment]
> The mouse had no fluid movements after starting Cura the first time but with the second start everything was fine (in case if one ask for this behavior)

That sounds a little odd. Can you check your cura.log file and look for the messages that show the RawMouse plugin being loaded and starting up. Perhaps something is not quite right.

**Comment by DivingDuck** [comment]
I stupidly did as well some other updates too and it seems there is a problem somewhere but it looks like it is not in your plugin (I guess). I attach the complete log files, maybe you have an idea. I need to remember what I did...

[curalog.zip](https://github.com/smartavionics/RawMouse/files/6341909/curalog.zip)

**Comment by smartavionics** [comment]
Thanks for the log files, it looks like RawMouse is loading and starting OK.
