### ISSUE TITLE
Use different view as 'fastview'

### ISSUE THREAD

**Issue by discip** [smartavionics/RawMouse#16]
Good morning @smartavionics,
now, since fastview works even in coexistence with Sidebar GUI, I am wondering, if it would be possible to use instead of the 'shadow' (footprint) of the part for fastview, the style of view, which is used in preview, as long as the part has not been sliced.

thanks in advance
kind regards

**Comment by smartavionics** [comment]
Hi, can you try the master branch? I've removed the shadow from the fastview.

**Comment by discip** [comment]
No, I was not bothered by the 'shadow', I just wondered if you could replace it by something like this:
I am referring only to the style not to this particular part.

![20210628_135020~01~01](https://user-images.githubusercontent.com/53649486/123633059-008db100-d819-11eb-9dae-dc50a4d32697.jpg)
Sometimes you need to know where you are zooming in on, but if there is nothing on the build plate you have to redo it some more times.

**Comment by smartavionics** [comment]
That looks rather like the x-ray view. Personally, I don't feel it looks better than the plainly rendered view that it provides now. I do think that removing the shadow is an improvement so thanks for inspiring me to do that!

**Comment by discip** [comment]
What plainly rendered view you are referring to?
In my case there is an empty build plate.

**Comment by smartavionics** [comment]
Here's the normal simulation view...

![Screenshot_2021-06-28_13-57-14](https://user-images.githubusercontent.com/585618/123640261-e48a0f80-d818-11eb-9b26-8d01a73154ab.png)

And here's the fast view ...

![Screenshot_2021-06-28_13-56-59](https://user-images.githubusercontent.com/585618/123640329-f79cdf80-d818-11eb-93e2-e8e2c0a7cb50.png)

**Comment by smartavionics** [comment]
Hmm, are you still using Aldo's sidebar thingy? Perhaps there's another compatibility issue?

**Comment by discip** [comment]
I assumed that too and disabled every single plugin, but with no effect what so ever.
Still empty built plate.

**Comment by smartavionics** [comment]
I just tried with the sidebar gui enabled and the fastview looks OK.

Maybe you have managed to corrupt the rawmouse files? Try saving the settings file, trashing the current rawmouse installation and installing from the current master and then copying the settings file back.

Yes, the cura.log file could have some useful messages...

**Comment by discip** [comment]
[logs.zip](https://github.com/smartavionics/RawMouse/files/6726528/logs.zip)

**Comment by smartavionics** [comment]
OK, the logs have shown the problem, standby for a fix...

**Comment by smartavionics** [comment]
Further investigation shows that the problem is due to some cura files (not rawmouse files) are using a deprecated feature that your graphics system is unhappy about...
```
2021-06-28 13:47:22,265 - DEBUG - [MainThread] UM.Controller.setActiveView [108]: Setting active view to FastView
2021-06-28 13:47:22,303 - DEBUG - [MainThread] UM.View.GL.ShaderProgram.load [59]: Loading shader file [C:\Program Files\Ultimaker Cura 4.10.0\resources\shaders\object.shader]...
2021-06-28 13:47:22,331 - ERROR - [MainThread] UM.View.GL.ShaderProgram.setVertexShader [129]: Vertex shader failed to compile: 0(8) : error C7555: 'attribute' is deprecated, use 'in/out' instead
0(9) : error C7555: 'attribute' is deprecated, use 'in/out' instead
0(10) : error C7555: 'attribute' is deprecated, use 'in/out' instead
```

The feature it is complaining about is used in other shader files so I would expect some other parts of your UI to be looking bad.

Right now, I don't have a fix. My first thought is that maybe your system has some option for the graphics that allows the shaders to use deprecated features?

**Comment by smartavionics** [comment]
Hi, please try the master branch again, I've worked around the issue (I think).

**Comment by discip** [comment]
@smartavionics
Good evening Sir,
it seems, that you ... **DIT IT!**
At least on one of the setups I am working with it works now as intended.
I will have to check it on the other setup tomorrow and if that is going to work as well, this will be closed.

## THANK YOU VERY MUCH 👍

**Comment by smartavionics** [comment]
👍

**Comment by discip** [comment]
Good morning,
works here as well!

Thank you!
