### ISSUE TITLE
'RawMouse' object has no attribute '_profile'

### ISSUE THREAD

**Issue by KenwoodFox** [smartavionics/RawMouse#18]
Im on linux using a 3D Connexion and getting this error.

```
2021-12-06 00:13:43,578 - ERROR - [MainThread] RawMouse.RawMouse._showDeviceInformation [549]: Exception while showing device information: 'RawMouse' object has no attribute '_profile'
```

Dosent seem to be working and this occures when i press the show device information button, not sure whats wrong exactly. The information box does not appear.

**Comment by smartavionics** [comment]
Hi, can you please provide the complete cura.log file (rename to cura.txt so you can attach it here). Thanks.

**Comment by KenwoodFox** [comment]
Sure thing!
[cura.log](https://github.com/smartavionics/RawMouse/files/7664205/cura.log)

**Comment by smartavionics** [comment]
Thanks for that. I can now see that you are using a different Python version from what RawMouse expects. However, it should work if you install the hid package from https://pypi.org/project/hid/. Hope this helps.

**Comment by KenwoodFox** [comment]
It shows up! still does not seem to accept any input but it does show up!

**Comment by KenwoodFox** [comment]
![image](https://user-images.githubusercontent.com/31870999/145115040-58676b6a-0014-4195-9281-5d825d2f10bd.png)

**Comment by KenwoodFox** [comment]
`hid` was the wrong package i think, `hidapi` was correct, but i still get

```
2021-12-08 20:34:32,353 - DEBUG - [RawMouse] RawMouse.RawMouse._run_hid [228]: Trying to open 5-3:1.1
2021-12-08 20:34:32,353 - ERROR - [RawMouse] RawMouse.RawMouse._run_hid [255]: IOError while reading HID events: open failed
```

Getting closer!

**Comment by smartavionics** [comment]
Ah, yes, sorry, it's hidapi.

Have you read the bit in the readme file about Linux permissions?

**Comment by KenwoodFox** [comment]
> Ah, yes, sorry, it's hidapi.
> 
> Have you read the bit in the readme file about Linux permissions?

Yes and ive setup the udev rules correctly i think, how could i test?
![image](https://user-images.githubusercontent.com/31870999/145485417-04000f95-8bae-4949-99f1-e0df59cc73b0.png)

**Comment by smartavionics** [comment]
Those permissions look OK.

Maybe the problem is that something else has opened the device exclusively so RawMouse can't open it.

Do you have a 3D connexion driver installed? Or any other software that could be accessing those devices?

**Comment by KenwoodFox** [comment]
I do actually yeah, the linux spacenavd daemon, let me try stopping that.

**Comment by KenwoodFox** [comment]
> 

Even with spacenavd stopped (light on the 3d mouse goes out) i still get the IOError :/ wonder what it could be

**Comment by smartavionics** [comment]
Don't know. Please post the latest cura.log so I can check if it's logging anything useful.

**Comment by KenwoodFox** [comment]
I was able to fix it by installing the appimage version.
