### ISSUE TITLE
Pitch axis and zoom crosstalk Cura 5.1

### ISSUE THREAD

**Issue by PeterGribbin** [smartavionics/RawMouse#21]
Using a spacemouse pro, when pitching back or forward, the view also zooms in or out.

I checked the config.json file and nothing seems amiss.

Other axis including the zoom axis work as intended.

Issue not present in Cura 4.x

**Comment by smartavionics** [comment]
Hi, I don't normally use Cura 5 but I downloaded a copy and, for me, RawMouse is working exactly as it does with Cura 4. There's no coupling between any axes.

**Comment by DivingDuck** [comment]
I do not have this problem with Cura 5.1 and the latest version of RawMouse (OS: Windows 10 64bit) but I know that is happen when you have 3Dconnexion with active application settings for Cura. Maybe worth to check (see attached picture). I attach my config file for comparison. It is set up to act like in Fusion 360.

![CuraRawMouse](https://user-images.githubusercontent.com/8143022/181716556-442852b5-4cef-4231-9b8d-d8784e5b83ec.PNG)

[config.zip](https://github.com/smartavionics/RawMouse/files/9218026/config.zip)

**Comment by PeterGribbin** [comment]
Fixed: Rotation was enabled in the 3d connexion setting for Cura 5.1. I turned it off and behaviour is now as intended, thanks DivingDuck.
