### ISSUE TITLE
All Axis inverted using SpaceNavigator

### ISSUE THREAD

**Issue by loneFunction** [smartavionics/RawMouse#4]
<img width="386" alt="Screen Shot 2020-05-15 at 4 59 36 PM" src="https://user-images.githubusercontent.com/5308216/82104903-8e6a1380-96cd-11ea-9797-13cf6b4bfd4a.png">
Using the Spacenavigator on MacOS, all movements are inverted by default.

**Comment by loneFunction** [comment]
It was easy enough to change by swapping the sign on the scaling.

**Comment by smartavionics** [comment]
Yes, that's what you do. The defaults are what I use, I don't expect them to suit everyone.
