### ISSUE TITLE
Not smooth movement

### ISSUE THREAD

**Issue by eried** [smartavionics/RawMouse#6]
Hi, thanks for the plugin. I was trying to find why the movement is not fully smooth like in inventor. It seems that Cura tries to adjust the zoom on some rotations:

![cura](https://user-images.githubusercontent.com/1091420/84497316-d705f400-acae-11ea-94a5-c54c6fa50c20.gif)

Side to side is all ok, and also zoom, but movements with more components there is a clear "stepped" zoom in/out. 

In your code I have already tried:
1. With the config.json (setting the values to high/low) and the (cura automatic) zoom step is the same
2. Removed zoom completely commenting:
![image](https://user-images.githubusercontent.com/1091420/84497446-192f3580-acaf-11ea-8f69-0d31f87eef0a.png)

There is no zoom as result, but cura adds that stepped zoom anyways

3. Making `_getScalingDueToZoom` to answer always 1.0, also not a fix.

Any hint what could be generate that stepped zoom?

**Comment by smartavionics** [comment]
Hi. Sorry, no, I don't know what is causing that. On Linux, I don't see a stepped zoom, all movements are reasonably smooth. Is it the same for both perspective and orthographic view modes?

**Comment by smartavionics** [comment]
Does it also behave like this if you disable the 3dconnextion driver?

**Comment by smartavionics** [comment]
You don't say what system you are using but I'm guessing Windows. On my Windows 10 laptop which is very slow and in every way under-performing, the movement in all axes is a little jittery but the zoom is no worse than the other axes.

**Comment by eried** [comment]
The movement is silky smooth with 3dxWare off :)

**Comment by eried** [comment]
Actually, if I open the settings in 3dxware and remove all functions on "cura.exe" then it is smooth everywhere keeping it on! :D

![image](https://user-images.githubusercontent.com/1091420/84659377-a1177880-af17-11ea-9a8a-62a17c3439e6.png)

**Comment by smartavionics** [comment]
OK, thanks for the update. Cheers!
