### ISSUE TITLE
Automatic Restart

### ISSUE THREAD

**Issue by eried** [smartavionics/RawMouse#7]
Hi again! How could I trigger an automatic reload on every windows switch/activation? 

For some reason under Windows (with the actions set to none in the official driver) this works perfectly but from time to time I need to call "Extensions / Rawmouse / Restart" to make it respond again. Usually after switching to Inventor for example. 

I would appreciate any tip how to code that, because I can see how undocumented is the development of cura plugins

**Comment by smartavionics** [comment]
Hi. Do you get any messages in cura.log that say "Exception while reading HID events" when it fails after switching away and returning?

**Comment by eried** [comment]
I only see

```
2020-06-15 16:01:25,005 - ERROR - [RawMouse] RawMouse.RawMouse._run_hid [243]: Exception while reading HID events: read error
2020-06-15 16:07:50,341 - DEBUG - [MainThread] cura.OAuth2.AuthorizationHelpers.getAccessTokenUsingRefreshToken [53]: Refreshing the access token.
2020-06-15 16:07:50,694 - DEBUG - [MainThread] cura.OAuth2.AuthorizationService._storeAuthData [213]: Attempting to store the auth data
```

but nothing recently. I will try to find a way to replate the error, but I think just reloading on window active would do the job.

**Comment by smartavionics** [comment]
> but I think just reloading on window active would do the job.

It would be nice to be able to detect when it's necessary to do a restart rather than restarting every time the focus is lost/restored by Cura.

**Comment by eried** [comment]
I know, but Restarting does not seem to be very resource intensive

**Comment by smartavionics** [comment]
Next time it occurs, look at the log and see if it produced a message, thanks.

**Comment by smartavionics** [comment]
The master branch now detects the read error and does a restart, could you please try that.

**Comment by eried** [comment]
Loaded, I will see if it happens again. Thanks! :)

**Comment by smartavionics** [comment]
Hi, has this fix been working OK for you?

**Comment by eried** [comment]
Yes! I have been using it since then and no more issues
